In [26]:
import pandas as pd

data = pd.read_csv('data_janji_jiwa.csv')
data

JARAK (KM)   ITK  INDRAKILA  GRAND CITY  MT. HARYONO  RUHUI RAHAYU  \
0           ITK   0.0       12.1        12.4         14.7          16.4   
1     INDRAKILA  12.1        0.0         3.3          3.7           5.4   
2    GRAND CITY  12.4        3.3         0.0          2.6           4.3   
3   MT. HARYONO  14.7        3.7         2.6          0.0           1.7   
4  RUHUI RAHAYU  16.4        5.4         4.3          1.8           0.0   
5    AHMAD YANI  20.5        6.2         9.0          6.8           7.9   

   AHMAD YANI  
0        20.5  
1         6.2  
2         9.0  
3         6.8  
4         7.9  
5         0.0

In [124]:
# Fungsi merubah posisi partikel menjadi rute
def pos2route(x):

    x_sorted = torch.sort(x)
    
    for i in range(len(x)):
        x[i] = x_sorted.indices[i+1]

    return x

# Fungsi menghitung jarak berdasarkan rute
def cal_distance(route):
    """
    distance = 0

    for i in range(len(route)):
        if i == 0:
            distance += data.iloc[0, int(route[i])+1]
        elif i == len(route)-1:
            distance += data.iloc[int(route[i-1]), int(route[i])+1] + data.iloc[int(route[i]), 1]
        else:
            distance += data.iloc[int(route[i-1]), int(route[i])+1]
    """ 
    distance = 2 * route
    #print(distance)
    
    return distance


# cost function
def cal_cost(x):

    x = pos2route(x)
    print(x)
    output = cal_distance(x)

    return output

In [125]:
import torch

def minimize(cost_func, initial_parameters, iterations, learning_rate):
    list_params = []
    params = initial_parameters
    params.requires_grad_()
    optimizer = torch.optim.SGD([params], learning_rate)

    for i in range(iterations):
        print(f"iter={i}")
        print(params)
        optimizer.zero_grad()
        print(params)
        loss = cost_func(params)
        print(loss)
        loss.backward()
        optimizer.step()
        list_params.append(params.detach().clone())
        
    return params, list_params

In [126]:
iterations = 20
starting_point = torch.tensor(np.float_(np.arange(1,6,1)))
learning_rate = .1
minimized_params, list_of_params = minimize(cal_cost, starting_point, iterations, learning_rate)

iter=0
tensor([1., 2., 3., 4., 5.], dtype=torch.float64, requires_grad=True)
tensor([1., 2., 3., 4., 5.], dtype=torch.float64, requires_grad=True)


RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

In [127]:
starting_point = torch.tensor(np.float_(np.array([3,2,6,4,2])))
starting_point

tensor([3., 2., 6., 4., 2.], dtype=torch.float64)

In [54]:
list_params = []
list_params

[]

In [128]:
params = starting_point
params

tensor([3., 2., 6., 4., 2.], dtype=torch.float64)

In [129]:
params.requires_grad_()
params

tensor([3., 2., 6., 4., 2.], dtype=torch.float64, requires_grad=True)

In [130]:
optimizer = torch.optim.SGD([params], learning_rate)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [131]:
optimizer.zero_grad()
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [132]:
params

tensor([3., 2., 6., 4., 2.], dtype=torch.float64, requires_grad=True)

In [134]:
x_sorted = torch.sort(params)
x_sorted

torch.return_types.sort(
values=tensor([2., 2., 3., 4., 6.], dtype=torch.float64, grad_fn=<SortBackward0>),
indices=tensor([1, 4, 0, 3, 2]))

In [141]:
x_sorted = x_sorted.indices

In [142]:
x_sorted

tensor([1, 4, 0, 3, 2])

In [137]:
a = x_sorted.indices + 1

In [140]:
for i in range(len(params)):
    params[i] = a[i]

RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

In [138]:
distance = 0

for i in range(len(a)):
    if i == 0:
        distance += data.iloc[0, int(a[i])+1]
    elif i == len(route)-1:
        distance += data.iloc[int(a[i-1]), int(a[i])+1] + data.iloc[int(a[i]), 1]
    else:
        distance += data.iloc[int(a[i-1]), int(a[i])+1]

In [139]:
distance

34.8