In [3]:
import pandas as pd
import numpy as np
import pygad

In [4]:
data = pd.read_csv('data1.csv')

In [5]:
data

Unnamed: 0  A  B  C  D  E  F
0          A  0  5  6  7  8  1
1          B  5  0  7  8  9  2
2          C  6  7  0  3  2  3
3          D  7  8  3  0  1  4
4          E  8  9  2  1  0  5
5          F  1  2  3  4  5  0

In [13]:
def cal_fitness(ga_instance, solution, solution_idx):
    #print(solution)
    pass
    #min_route = np.sum(solution)

    #return -min_route
    return 0

In [14]:
len(data)

6

In [15]:
def on_generation(ga):
    print("Generation", ga.generations_completed)
    print(ga.population)

In [16]:
ga_instance = pygad.GA(num_generations = 10,
                       num_parents_mating = 2,
                       fitness_func = cal_fitness,
                       sol_per_pop = 10,
                       num_genes = 5,
                       gene_type = int,
                       gene_space = np.arange(5),
                       allow_duplicate_genes=False,
                       on_generation=on_generation
                       )

/home/fafa/miniconda3/envs/py311/lib/python3.11/site-packages/pygad/pygad.py:728: UserWarning: The percentage of genes to mutate (mutation_percent_genes=10) resulted in selecting (0) genes. The number of genes to mutate is set to 1 (mutation_num_genes=1).
If you do not want to mutate any gene, please set mutation_type=None.
  warnings.warn(
/home/fafa/miniconda3/envs/py311/lib/python3.11/site-packages/pygad/pygad.py:1139: UserWarning: The 'delay_after_gen' parameter is deprecated starting from PyGAD 3.3.0. To delay or pause the evolution after each generation, assign a callback function/method to the 'on_generation' parameter to adds some time delay.
  warnings.warn("The 'delay_after_gen' parameter is deprecated starting from PyGAD 3.3.0. To delay or pause the evolution after each generation, assign a callback function/method to the 'on_generation' parameter to adds some time delay.")


In [17]:
ga_instance.run()

Generation 1
[[0 1 4 2 3]
 [2 1 0 3 4]
 [2 0 4 3 1]
 [0 1 4 2 3]
 [3 2 4 1 0]
 [1 0 4 2 3]
 [2 3 4 1 0]
 [0 1 4 2 3]
 [0 1 4 2 3]
 [0 1 3 2 4]]
Generation 2
[[0 1 3 2 4]
 [0 1 3 2 4]
 [0 1 4 2 3]
 [2 1 4 0 3]
 [0 4 1 2 3]
 [0 1 3 2 4]
 [0 1 3 2 4]
 [0 1 3 2 4]
 [0 1 4 2 3]
 [0 1 3 2 4]]
Generation 3
[[0 1 3 2 4]
 [0 1 4 2 3]
 [0 4 1 2 3]
 [0 1 4 2 3]
 [0 1 3 2 4]
 [0 1 3 2 4]
 [1 0 3 2 4]
 [0 1 3 2 4]
 [0 1 3 2 4]
 [2 1 3 0 4]]
Generation 4
[[2 1 3 0 4]
 [2 1 3 0 4]
 [2 1 3 0 4]
 [3 1 2 0 4]
 [2 1 3 0 4]
 [2 1 3 0 4]
 [0 1 3 2 4]
 [2 1 3 0 4]
 [0 3 1 2 4]
 [2 1 3 0 4]]
Generation 5
[[2 1 3 0 4]
 [2 3 1 0 4]
 [0 3 1 2 4]
 [2 1 3 0 4]
 [3 1 2 0 4]
 [3 1 2 0 4]
 [0 1 3 2 4]
 [2 1 3 0 4]
 [0 4 3 2 1]
 [4 3 1 0 2]]
Generation 6
[[4 3 1 0 2]
 [0 4 3 2 1]
 [0 4 3 2 1]
 [4 3 0 2 1]
 [0 2 3 1 4]
 [4 2 0 3 1]
 [0 4 3 2 1]
 [0 4 3 2 1]
 [4 0 1 3 2]
 [4 2 0 3 1]]
Generation 7
[[4 2 0 3 1]
 [4 0 1 3 2]
 [4 0 1 3 2]
 [4 2 0 3 1]
 [4 0 3 2 1]
 [4 0 1 3 2]
 [4 0 1 3 2]
 [4 0 3 1 2]
 [2 4 0 3 1]
 [1 2 